# Generated by Django 4.0.4 on 2022-08-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edycje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_1', models.FileField(upload_to='')),
                ('slide_2', models.FileField(upload_to='')),
                ('slide_3', models.FileField(upload_to='')),
                ('o_nas_tytul', models.CharField(max_length=300)),
                ('o_nas_opis', models.TimeField(max_length=2000)),
                ('tel_1', models.CharField(max_length=20)),
                ('tel_2', models.CharField(max_length=20)),
                ('regulamin', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Edycja',
                'verbose_name_plural': 'Edycje',
            },
        ),
    ]
