# Generated by Django 4.0.4 on 2022-08-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_edycje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edycje',
            name='o_nas_opis',
            field=models.TextField(max_length=2000),
        ),
    ]
